### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/node-btcpay#1]
hey @takinbo, I am tempted to play and convert to typescript.
Would you be open to such PR?

**Comment by Uter1007** [comment]
could also help out here. PM me ;) cheers Christoph

**Comment by takinbo** [comment]
@Uter1007 by all means.

**Comment by Uter1007** [comment]
can you create a branch where I am allowed to create a project for that ? or should I create a new repository.

**Comment by takinbo** [comment]
@Uter1007 you could fork the repo and submit a PR when you are ready

**Comment by Uter1007** [comment]
https://github.com/btcpayserver/node-btcpay/pull/12
