### ISSUE TITLE
get_rate return 404

### ISSUE THREAD

**Issue by murqacher** [btcpayserver/node-btcpay#2]
```
let btc = new btcpay.BTCPayClient('https://btcpay-server-testnet.azurewebsites.net', KeyPair, {merchant: '...'})
btc.get_rate('BTC_USD').then(rate => console.log(rate))
```
return `Unhandled rejection StatusCodeError: 404 - undefined` on server: https://btcpay-server-testnet.azurewebsites.net

**Comment by Uter1007** [comment]
got the same error - could you provide your solution or what did I do wrong ?
