### ISSUE TITLE
Unable to generate private key in node v11.15.0

### ISSUE THREAD

**Issue by Alko89** [btcpayserver/node-btcpay#20]
Trying to generate private key using `node -p "require('btcpay').crypto.generate_keypair()"` returns a large object instead of the private key.

Using the same command with node v10.16.0 works as expected:

    <Key priv: c5e246de8c156c607658391641d42a1040914c78509c76acc8752947dd4ff091 pub: null >
    (node:26425) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

**Comment by NicolasDorier** [comment]
@takinbo any idea?

**Comment by takinbo** [comment]
@Alko89 what version of node gives you the large object?

**Comment by Alko89** [comment]
On v11.15.0. Downgrading solved the issue.

**Comment by johnbailon** [comment]
You can do this instead:
```bash
node -p "require('btcpay').crypto.generate_keypair().getPrivate('hex')"
```

**Comment by NicolasDorier** [comment]
@takinbo I guess the doc somewhere is outdated.

**Comment by NicolasDorier** [comment]
fixed by https://github.com/btcpayserver/node-btcpay/pull/32

**Comment by AryanJ-NYC** [comment]
I ran into this same docs bug. I noticed #32 was merged into branch `btcpayserver:dev` and not `master`. This may confuse users that try to use this library for the first time.
