### ISSUE TITLE
Syntax Issue w/ Pairing

### ISSUE THREAD

**Issue by lnCraf** [btcpayserver/node-btcpay#27]
When trying to pair client to my store, I get a syntax error here: https://pastebin.com/Nf5xgkWb

Seems to have something to do with the store URL. Please help, I'm a novice programmer and have been stuck trying to resolve this for many hours now.

(FYI, I removed my priv key and pairing code in the shared example)

**Comment by lnCraf** [comment]
Ok, so I was able to remove the syntax error by creating a .env file and storing the store/key/paircode values in there. But then when I execute the suggested code I get "throw new ERR_INVALID_ARG_TYPE."

**Comment by takinbo** [comment]
@lnCraf the issue appears to be related with the statement `new btcpay.BTCPayClient(process.env.https://btcpay435016.lndyn.com)`. Rather then putting the explicit url here, you should set the `BTCPAY_URL` value in the environment and use `new btcpay.BTCPayClient(process.env.BTCPAY_URL)` or explicitly set it to `new btcpay.BTCPayClient('btcpay435016.lndyn.com')`.

**Comment by lnCraf** [comment]
Thanks for the help @takinbo . I gave that a try, and now I'm getting this error when running it: https://imgur.com/a/PhhqZyN

**Comment by takinbo** [comment]
@lnCraf you need to specify the values for `BTCPAY_URL`, `BTCPAY_KEY` and `BTCPAY_PAIRCODE` as specified from the previous steps so your invocation command should be:

```
BTCPAY_URL="https://btcpay435016.lndyn.com" BTCPAY_KEY="whateveryourkeywas" BTCPAY_PAIRCODE="yourpairingcode" node -e ...
```

Please replace the `...` with the remaining of the command you have been using. More information about the process is in the project's [README](https://github.com/btcpayserver/node-btcpay/blob/master/README.md)

**Comment by lnCraf** [comment]
@takinbo I did specify them in my .env file, still got the error though

**Comment by takinbo** [comment]
`.env` files do not populate environment variables and so are not being used here. This is why the instructions set the environment variables in the same line as the invocation.

**Comment by lnCraf** [comment]
It may be a Windows specific issue, but I had errors setting the environment variables in the same line as the invocation. I was able to resolve the issue by removing "process.env" and just putting the values in directly. While probably not best practice, it worked for now. May be worth mentioning this in the .readme

**Comment by takinbo** [comment]
Thanks @lnCraf. We would work on updating the README from this feedback.
