### ISSUE TITLE
BTCPayServer cannot authenticate with node-btcpay client

### ISSUE THREAD

**Issue by busternr** [btcpayserver/node-btcpay#3]
I am using the latest versions of BTCPayServer & NBXplorer & current version of node-btcpay. When I try to make invoice thought node-btcpay I get this in the logs of BTCPayServer: 
![export](https://user-images.githubusercontent.com/15079119/44138417-8a90211c-a07c-11e8-8da4-6b8aaf4b44ab.png)
...and nodejs console logs error 401
Code:
`let btcpay = require("btcpay");
var keypair = btcpay.crypto.generate_keypair();
var client = new btcpay.BTCPayClient("http://127.0.0.1:23001", keypair, {
    merchant: "TfGH9Np8qCtc61Hjk44jK6677GPr6JSv2QW"
});
client.create_invoice({"price": 20, "currency": "USD"}).then(invoice => console.log(invoice.url))`

**Comment by takinbo** [comment]
@busternr it appears you are generating a new keypair each time you create a client connection. The keypair generation should only be done once and saved before pairing. After pairing, you can then use the merchant code with the keypair to create invoices.

**Comment by takinbo** [comment]
@busternr we just had better documentation contributed by @danlutz added to the project. You may want to take a look at that and see if it better explains what you should do.
