### ISSUE TITLE
Email confirmations?

### ISSUE THREAD

**Issue by chovy** [btcpayserver/node-btcpay#34]
Is it possible to send the customer an email confirmation?

BTCPayServer has an SMTP server setup, but I'm not getting any confirmation emails either as the customer or the merchant.

**Comment by NicolasDorier** [comment]
no, there is no API exposing this.

**Comment by NicolasDorier** [comment]
Though you can take a look at the btcpayserver transmutter by @Kukks .

This is an additional project which complement btcpay to do some automation like this. (come on the mattermost, we have a channel for that)

**Comment by takinbo** [comment]
As @NicolasDorier mentioned, BTCPayserver does not send payment confirmation emails and you would need to do that independently.
