### ISSUE TITLE
support for other currencies?

### ISSUE THREAD

**Issue by chovy** [btcpayserver/node-btcpay#35]
BTCPayServer supports other currencies, does this library handle that?

I have a gateway that accepts ltc, doge, btc, monero and dash.

**Comment by NicolasDorier** [comment]
there is nothing specific to altcoins in the invoice API so it should work

**Comment by chovy** [comment]
how do i say which coin to create an invoice for?

**Comment by NicolasDorier** [comment]
it is in your store configuration.

**Comment by chovy** [comment]
I want to allow users to select which coin to pay with. I need this library to pass that to the api so it generate an address, amount and qrcode for the right coin.

**Comment by NicolasDorier** [comment]
Same as bitpay, we use `supportedTransactionCurrencies`

**Comment by chovy** [comment]
I think you're not understanding.

**Comment by NicolasDorier** [comment]
```
supportedTransactionCurrencies: 
{
"BTC": true
}
```
should only activate btc

**Comment by chovy** [comment]
How do I specify an invoice for LTC?

**Comment by NicolasDorier** [comment]
```
supportedTransactionCurrencies: 
{
"LTC": true
}
```

**Comment by chovy** [comment]
where do i pass this? can you give me a full example?

**Comment by NicolasDorier** [comment]
Ready https://bitpay.com/api/#rest-api-resources-invoices-resource 

supportedTransactionCurrencies

I can't give you the code, I don't code in node.

**Comment by takinbo** [comment]
https://bitpay.com/api/#rest-api-resources-invoices-create-an-invoice contains instructions on how to pass the currency(ies) you want to accept the payment in. The parameter is called `paymentCurrencies`.

**Comment by takinbo** [comment]
@chovy according to https://bitpay.com/api/#rest-api-resources-invoices-create-an-invoice you should specify the payment currency this way:
```js
client.create_invoice({price: 20, currency: 'USD', paymentCurrencies: ['LTC'])
    .then(invoice => console.log(invoice))
    .catch(err => console.error(err));
```

**Comment by takinbo** [comment]
Closing out old issues. If the issue persists, please open a new issue.
