### ISSUE TITLE
TypeScript Crypto issue

### ISSUE THREAD

**Issue by digimbyte** [btcpayserver/node-btcpay#43]
Building my project in TypeScript and I have the following issues regarding Crypto

> node_modules/btcpay/dist/core/cryptography.d.ts:8:33 - error TS2694: Namespace '"crypto"' has no exported member 'BinaryLike'.
> 8     static sign(message: crypto.BinaryLike, kp: elliptic.ec.KeyPair): Buffer;
https://nodejs.org/docs/latest-v12.x/api/crypto.html

Any alternatives for v12 LTS?
node -v
v12.8.0

**Comment by digimbyte** [comment]
Solution: import Node Types
`npm install @types/node`

**Comment by takinbo** [comment]
For future reference: the `@types/node` package is already dev dependency.
