### ISSUE TITLE
How can I automatically fill in the refund-email

### ISSUE THREAD

**Issue by Preisschild** [btcpayserver/node-btcpay#8]
I currently use it like this: 
 
```
client.create_invoice({price: 2, currency: 'EUR'})
        .then(invoice => console.log(invoice.url))
        .catch(err => console.log(err))
  });
```

How can I make btcpay automatically fill in the E-Mail address? 

I already tried 
```
client.create_invoice({price: 2, currency: 'EUR', email: 'z@example.org'})
        .then(invoice => console.log(invoice.url))
        .catch(err => console.log(err))
  });
```
which is not working

also @NicolasDorier said that it is buyer.email, which I also tried like this:
```
client.create_invoice({price: 2, currency: 'EUR', 'buyer.email': 'z@example.org'})
        .then(invoice => console.log(invoice.url))
        .catch(err => console.log(err))
  });
```
but it also isn't working

**Comment by NicolasDorier** [comment]
can you post the solution?

**Comment by Preisschild** [comment]
Since I only wanted to not see the refund-email-page it was enough for me to just uncheck the "Requires a refund email" button in Stores>Checkout experience.

Can reopen If theres a need for a filled in e-mail-address. But I don't think there is.

**Comment by NicolasDorier** [comment]
`{price: 2, currency: 'EUR', 'buyer': { 'email': 'z@example.org' }}` should work
