### ISSUE TITLE
Cannot get token

### ISSUE THREAD

**Issue by hazratgs** [btcpayserver/node-btcpay#9]
guys trying to get a token, doing everything according to the instructions, but does not work (at the end of an error 403

Is the instruction really working?

**Comment by NicolasDorier** [comment]
what do you mean 'at the end'? when you do create invoice?

**Comment by takinbo** [comment]
@hazratgs Could you also share what statements you are invoking to get to the point of getting a 403 error?

**Comment by hazratgs** [comment]
> @hazratgs Could you also share what statements you are invoking to get to the point of getting a 403 error?

The guys when I try to create an invoice, I constantly have a 401 error, although I do everything according to the instructions:
```info: BTCPayServer.Security.BitpayAuthentication+BitpayAuthHandler: Bitpay.Auth was not authenticated. Failure message: Invalid credentials
info: BTCPayServer.Security.BitpayAuthentication+BitpayAuthHandler: AuthenticationScheme: Bitpay.Auth was challenged.```

perform the following steps:

- create a private key
- I get clientId using it (that is, I get SIN)
- I create a new token in the admin panel btcpayserver-> stores-> Access token
- copying the pairing code and sending a request to / tokens, the request looks like this: body {pairingCode: 'j6jfkaf', id: 'Tf3WxtCNvPR9ATBjc14Wrw6EBxBS5AWn8Li'}
- in response, I successfully receive the token
- then I create an invoice {price: 900, currency: 'USD', token: '****'}
- add X-Identity and X-Signature headers
```{
'X-Identity': Buffer.from(this.keypar.getPublic().EncodeCompressed()).ToString('hex'),
'X-Signature': this.sign(url, this.keypar).toString ('hex')
}```
where url is this.url + uri + payload, and payload is JSON request body

I end up with a 401 error (edited)

**Comment by takinbo** [comment]
@hazratgs not sure if this is still an issue (considering how long it has been) but if it still is, can you give the list of steps you took to the point where you are unable to get a token?

**Comment by PeerZetZzZzZ** [comment]
@takinbo some time later but I struggle with the same issue.

Error from BtcPay:
info: BTCPayServer.Security.Bitpay.BitpayAuthenticationHandler: Bitpay was not authenticated. Failure message: BitId authentication failed
info: BTCPayServer.Security.Bitpay.BitpayAuthenticationHandler: AuthenticationScheme: Bitpay was challenged.

what's funny that the post calling script (console.log) shows me that the payload body is '{"price":20,"currency":"USD","token":"3ySSfoS3Zbiza1ARycUrNA473xUvRdajctnX9xoruJ1b"}', and token matches the one visible in BtcPay.

**Comment by takinbo** [comment]
Good to know :rocket:
